service: recommender-api-service
app: recommenderapi
tenant: amanneox
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  createPost:
    handler: handlers/PostHandler.createPost
    events:
      - http:
          path: post/{id}
          method: post
          cors: true

  getPost:
   handler: handlers/PostHandler.getPost
   events:
     - http:
         path: post/{id}
         method: get
         cors: true

  getPosts:
    handler: handlers/PostHandler.getPosts
    events:
      - http:
          path: posts/list
          method: get
          cors: true

  updatePost:
    handler: handlers/PostHandler.updatePost
    events:
      - http:
          path: post/update/{id}
          method: post
          cors: true

  deletePost:
    handler: handlers/PostHandler.deletePost
    events:
      - http:
          path: post/delete/{id}
          method: get
          cors: true

  createCategory:
    handler: handlers/CategoryHandler.createCategory
    events:
      - http:
          path: category
          method: post
          cors: true
  getCategory:
    handler: handlers/CategoryHandler.getCategory
    events:
      - http:
          path: category/list
          method: get

  createComment:
    handler: handlers/CommentHandler.createComment
    events:
      - http:
          path: comment/{id}
          method: post
          cors: true

  getComments:
    handler: handlers/CommentHandler.getComments
    events:
      - http:
          path: comment/list/{id}
          method: get

  createRating:
    handler: handlers/RatingHandler.createRating
    events:
      - http:
          path: rating/{id}
          method: post
          cors: true

  getRatings:
    handler: handlers/RatingHandler.getRatings
    events:
      - http:
          path: rating/list/{id}
          method: get

  createReport:
    handler: handlers/ReportHandler.createReport
    events:
      - http:
          path: report/{id}
          method: post
          cors: true
